name: staging

on:
  push:
    branches:
      - main
    paths:
      - staging/**
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      FEAST_VERSION: "0.11.0"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install Feast
        run: pip install 'feast[gcp]=='$FEAST_VERSION
      - name: Update Feature Store Infrastructure
        run: |
          cd staging
          feast apply